# Render.com deployment configuration with cache fixes
services:
  - type: web
    name: helix-regulatory-platform
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      # Apply complete deployment cache permission fixes
      export NPM_CONFIG_CACHE=/tmp/.npm-cache
      export NPM_CONFIG_TMP=/tmp
      export NPM_CONFIG_INIT_CACHE=/tmp/.npm-init
      export NPM_CONFIG_GLOBALCONFIG=/tmp/.npmrc-global
      export NPM_CONFIG_USERCONFIG=/tmp/.npmrc-user
      export DISABLE_NPM_CACHE=true
      export DISABLE_OPENCOLLECTIVE=true
      export NODE_OPTIONS="--max-old-space-size=4096 --max-semi-space-size=1024"
      export PORT=5000
      export KEEP_DEV_DEPENDENCIES=true
      export NPM_CONFIG_PROGRESS=false
      export NPM_CONFIG_LOGLEVEL=warn
      export NPM_CONFIG_AUDIT=false
      export NPM_CONFIG_FUND=false
      export NPM_CONFIG_UPDATE_NOTIFIER=false
      export NPM_CONFIG_PACKAGE_LOCK=false
      export NPM_CONFIG_SHRINKWRAP=false
      
      # Clear cache and create writable directories before building
      rm -rf node_modules/.cache || true
      rm -rf ~/.npm || true
      rm -rf /tmp/.npm* || true
      
      # Create all writable directories with proper permissions
      mkdir -p /tmp/.npm /tmp/.npm-init /tmp/.npm-global /tmp/.npm-user
      chmod -R 755 /tmp/.npm*
      
      # Create npm config files in writable locations
      echo "cache=/tmp/.npm-cache" > /tmp/.npmrc-global
      echo "tmp=/tmp" >> /tmp/.npmrc-global
      echo "fund=false" >> /tmp/.npmrc-global
      echo "audit=false" >> /tmp/.npmrc-global
      
      # Clear npm cache safely and install
      npm cache clean --force || true
      npm install --cache=/tmp/.npm-cache --tmp=/tmp --no-audit --no-fund --loglevel=warn --userconfig=/tmp/.npmrc-user --globalconfig=/tmp/.npmrc-global --include=dev
      npm run build
    startCommand: |
      # Start with production environment variables
      export NPM_CONFIG_CACHE=/tmp/.npm-cache
      export NODE_OPTIONS="--max-old-space-size=4096"
      export NODE_ENV=production
      npm run start
    envVars:
      - key: NPM_CONFIG_CACHE
        value: /tmp/.npm-cache
      - key: NPM_CONFIG_TMP
        value: /tmp
      - key: NPM_CONFIG_INIT_CACHE
        value: /tmp/.npm-init
      - key: NPM_CONFIG_GLOBALCONFIG
        value: /tmp/.npmrc-global
      - key: NPM_CONFIG_USERCONFIG
        value: /tmp/.npmrc-user
      - key: DISABLE_NPM_CACHE
        value: true
      - key: DISABLE_OPENCOLLECTIVE
        value: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096 --max-semi-space-size=1024
      - key: PORT
        value: 5000
      - key: KEEP_DEV_DEPENDENCIES
        value: true
      - key: NPM_CONFIG_PROGRESS
        value: false
      - key: NPM_CONFIG_LOGLEVEL
        value: warn
      - key: NPM_CONFIG_AUDIT
        value: false
      - key: NPM_CONFIG_FUND
        value: false
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: false
      - key: NPM_CONFIG_PACKAGE_LOCK
        value: false
      - key: NPM_CONFIG_SHRINKWRAP
        value: false
      - key: NODE_ENV
        value: production