services:
  - type: web
    name: helix-regulatory-platform
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: helix-postgres
          property: connectionString
    autoDeploy: true

databases:
  - name: helix-postgres
    databaseName: helix_db
    user: helix_user
    plan: starter