# Render.com deployment configuration with cache fixes
services:
  - type: web
    name: helix-regulatory-platform
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      # Apply comprehensive cache fixes before build
      export NPM_CONFIG_CACHE=/tmp/.npm
      export DISABLE_NPM_CACHE=true
      export DISABLE_OPENCOLLECTIVE=true
      export NODE_OPTIONS="--max-old-space-size=4096"
      export KEEP_DEV_DEPENDENCIES=true
      export NPM_CONFIG_PROGRESS=false
      export NPM_CONFIG_LOGLEVEL=warn
      export NPM_CONFIG_AUDIT=false
      export NPM_CONFIG_FUND=false
      export NPM_CONFIG_UPDATE_NOTIFIER=false
      
      # Clear all cached files and directories
      rm -rf node_modules/.cache
      rm -rf .cache
      rm -rf ~/.npm
      rm -rf /tmp/.npm
      npm cache clean --force
      
      # Create npm cache directory with proper permissions
      mkdir -p /tmp/.npm
      chmod 755 /tmp/.npm
      
      # Verify directory permissions and workspace path
      echo "Cache directory permissions:"
      ls -la /tmp/.npm
      echo "Current workspace: $(pwd)"
      
      # Build with cache disabled, keep dev dependencies, and verbose logging
      npm install --no-cache --verbose --include=dev
      npm run build
    startCommand: |
      # Start with production environment variables
      export NPM_CONFIG_CACHE=/tmp/.npm
      export NODE_OPTIONS="--max-old-space-size=4096"
      export NODE_ENV=production
      npm run start
    envVars:
      - key: NPM_CONFIG_CACHE
        value: /tmp/.npm
      - key: DISABLE_NPM_CACHE
        value: true
      - key: DISABLE_OPENCOLLECTIVE
        value: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: KEEP_DEV_DEPENDENCIES
        value: true
      - key: NPM_CONFIG_PROGRESS
        value: false
      - key: NPM_CONFIG_LOGLEVEL
        value: warn
      - key: NPM_CONFIG_AUDIT
        value: false
      - key: NPM_CONFIG_FUND
        value: false
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000