# Render.com deployment configuration with cache fixes
services:
  - type: web
    name: helix-regulatory-platform
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      # Apply comprehensive cache fixes before build
      export NPM_CONFIG_CACHE=/tmp/.npm
      export NPM_CONFIG_TMP=/tmp
      export NPM_CONFIG_INIT_CACHE=/tmp/.npm-init
      export DISABLE_NPM_CACHE=true
      export DISABLE_OPENCOLLECTIVE=true
      export NODE_OPTIONS="--max-old-space-size=4096 --max-semi-space-size=1024"
      export PORT=5000
      export KEEP_DEV_DEPENDENCIES=true
      export NPM_CONFIG_PROGRESS=false
      export NPM_CONFIG_LOGLEVEL=warn
      export NPM_CONFIG_AUDIT=false
      export NPM_CONFIG_FUND=false
      export NPM_CONFIG_UPDATE_NOTIFIER=false
      
      # Clear cache and create writable directories before building
      rm -rf node_modules/.cache
      rm -rf ~/.npm/_cacache
      rm -rf /tmp/.npm
      rm -rf /tmp/.npm-init
      
      # Create writable directories with proper permissions
      mkdir -p /tmp/.npm
      mkdir -p /tmp/.npm-init
      chmod 755 /tmp/.npm
      chmod 755 /tmp/.npm-init
      
      # Verify directory creation
      echo "Created cache directories:"
      ls -la /tmp/.npm /tmp/.npm-init
      echo "Current workspace: $(pwd)"
      
      # Install and build with enhanced cache settings
      npm install --cache=/tmp/.npm --tmp=/tmp --no-audit --no-fund --loglevel=warn --include=dev
      npm run build
    startCommand: |
      # Start with production environment variables
      export NPM_CONFIG_CACHE=/tmp/.npm
      export NODE_OPTIONS="--max-old-space-size=4096"
      export NODE_ENV=production
      npm run start
    envVars:
      - key: NPM_CONFIG_CACHE
        value: /tmp/.npm
      - key: NPM_CONFIG_TMP
        value: /tmp
      - key: NPM_CONFIG_INIT_CACHE
        value: /tmp/.npm-init
      - key: DISABLE_NPM_CACHE
        value: true
      - key: DISABLE_OPENCOLLECTIVE
        value: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096 --max-semi-space-size=1024
      - key: PORT
        value: 5000
      - key: KEEP_DEV_DEPENDENCIES
        value: true
      - key: NPM_CONFIG_PROGRESS
        value: false
      - key: NPM_CONFIG_LOGLEVEL
        value: warn
      - key: NPM_CONFIG_AUDIT
        value: false
      - key: NPM_CONFIG_FUND
        value: false
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: false
      - key: NODE_ENV
        value: production