name: helix-medtech
services:
- name: web
  source_dir: /
  github:
    repo: ihr-username/helix-project
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_SECRET
    value: your-secret-key-here
  - key: GMAIL_USER
    value: deltawaysnewsletter@gmail.com
  - key: GMAIL_PASS
    value: your-gmail-password
  
databases:
- name: helix-db
  engine: PG
  version: "13"
