# Helix Regulatory Intelligence - Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Helix Application Metrics
  - job_name: 'helix-app'
    static_configs:
      - targets: ['helix-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Cache Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Custom API Health Checks
  - job_name: 'helix-health'
    static_configs:
      - targets: ['helix-app:3000']
    metrics_path: '/api/health'
    scrape_interval: 60s
    scrape_timeout: 30s

  # External API Monitoring
  - job_name: 'fda-api'
    static_configs:
      - targets: ['api.fda.gov:443']
    metrics_path: '/device/recall.json'
    scheme: https
    scrape_interval: 300s
    scrape_timeout: 30s

  - job_name: 'ema-api'
    static_configs:
      - targets: ['www.ema.europa.eu:443']
    scheme: https
    scrape_interval: 300s
    scrape_timeout: 30s